# Generated by Django 5.2.9 on 2026-01-06 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('sequence', models.PositiveIntegerField(db_index=True)),
                ('diary_date', models.DateField(default=django.utils.timezone.localdate)),
                ('received_from', models.CharField(blank=True, default='', max_length=255)),
                ('received_diary_no', models.CharField(blank=True, default='', max_length=100)),
                ('file_letter', models.CharField(blank=True, default='', max_length=100)),
                ('no_of_folders', models.PositiveIntegerField(default=0)),
                ('subject', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('marked_to', models.CharField(blank=True, default='', max_length=255)),
                ('marked_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diaries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-sequence'],
            },
        ),
        migrations.CreateModel(
            name='DiaryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('sequence', models.PositiveIntegerField(db_index=True)),
                ('from_office', models.CharField(blank=True, default='', max_length=255)),
                ('to_office', models.CharField(blank=True, default='', max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('action_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_created', to=settings.AUTH_USER_MODEL)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='diary.diary')),
            ],
            options={
                'ordering': ['action_datetime', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('year', 'sequence'), name='uniq_diary_year_seq'),
        ),
    ]
