# Generated by Django 5.2.9 on 2026-01-06 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Created', 'Created'), ('Marked', 'Marked'), ('Forwarded', 'Forwarded'), ('Returned', 'Returned'), ('Closed', 'Closed'), ('Disposed', 'Disposed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='diarymovement',
            name='action_type',
            field=models.CharField(choices=[('Created', 'Created'), ('Marked', 'Marked'), ('Forwarded', 'Forwarded'), ('Returned', 'Returned'), ('Closed', 'Closed'), ('Disposed', 'Disposed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='diarymovement',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='diarymovement',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['year', 'sequence'], name='diary_diary_year_2c6b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['diary_date'], name='diary_diary_diary_d_e6f1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['status'], name='diary_diary_status_3bb377_idx'),
        ),
        migrations.AddIndex(
            model_name='diarymovement',
            index=models.Index(fields=['year', 'sequence'], name='diary_diary_year_fd9f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='diarymovement',
            index=models.Index(fields=['action_type'], name='diary_diary_action__23697f_idx'),
        ),
        migrations.AddIndex(
            model_name='diarymovement',
            index=models.Index(fields=['action_datetime'], name='diary_diary_action__bd2315_idx'),
        ),
    ]
