# Generated by Django 5.2.9 on 2026-01-07 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['received_diary_no'], name='diary_diary_receive_0830c6_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['received_from'], name='diary_diary_receive_24d2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['file_letter'], name='diary_diary_file_le_4919db_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['marked_to'], name='diary_diary_marked__8a2b19_idx'),
        ),
    ]
