# Generated by Django 4.2.30 on 2026-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_diary_diary_receive_0830c6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate_name', models.CharField(blank=True, default='', help_text='Name of the directorate for PDF reports. If blank, reports will use generic title.', max_length=255)),
                ('port', models.PositiveIntegerField(default=8000, help_text='Port number for the Django application.')),
                ('host', models.CharField(default='0.0.0.0', help_text='Host/IP address to bind the application to.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Configuration',
                'verbose_name_plural': 'App Configuration',
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='service_included',
            field=models.BooleanField(default=False),
        ),
    ]
